
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.productadmin;

import java.util.ArrayList;
import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mozu.api.contracts.productadmin.Attribute;
import com.mozu.api.contracts.productadmin.AttributeVocabularyValueInProductType;


/**
*	A product type is like a product template that can be reused in the product admin service. Assign a product type to have certain attributes.
*/
public class AttributeInProductType implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	/**
	*The fully qualified name of the attribute, which is a user defined attribute identifier.
	*/
	@JsonProperty("AttributeFQN")
	protected String attributeFQN;

	public String getAttributeFQN() {
		return this.attributeFQN;
	}

	public void setAttributeFQN(String attributeFQN) {
		this.attributeFQN = attributeFQN;
	}

	/**
	*If true, this property is hidden on the storefront. If false, this property is not hidden from the storefront.
	*/
	@JsonProperty("IsHiddenProperty")
	protected Boolean isHiddenProperty;

	public Boolean getIsHiddenProperty() {
		return this.isHiddenProperty;
	}

	public void setIsHiddenProperty(Boolean isHiddenProperty) {
		this.isHiddenProperty = isHiddenProperty;
	}

	/**
	*If true, this entity is inherited from the base type. If false, this entity is not inherited from the base type.
	*/
	@JsonProperty("IsInheritedFromBaseType")
	protected Boolean isInheritedFromBaseType;

	public Boolean getIsInheritedFromBaseType() {
		return this.isInheritedFromBaseType;
	}

	public void setIsInheritedFromBaseType(Boolean isInheritedFromBaseType) {
		this.isInheritedFromBaseType = isInheritedFromBaseType;
	}

	/**
	*If true, this attribute has more than one possible value.
	*/
	@JsonProperty("IsMultiValueProperty")
	protected Boolean isMultiValueProperty;

	public Boolean getIsMultiValueProperty() {
		return this.isMultiValueProperty;
	}

	public void setIsMultiValueProperty(Boolean isMultiValueProperty) {
		this.isMultiValueProperty = isMultiValueProperty;
	}

	/**
	*If true, the entity is required by the admin. If false, the entity is not required by the admin.
	*/
	@JsonProperty("IsRequiredByAdmin")
	protected Boolean isRequiredByAdmin;

	public Boolean getIsRequiredByAdmin() {
		return this.isRequiredByAdmin;
	}

	public void setIsRequiredByAdmin(Boolean isRequiredByAdmin) {
		this.isRequiredByAdmin = isRequiredByAdmin;
	}

	/**
	*The sequence of this attribute within its product type.
	*/
	@JsonProperty("Order")
	protected Integer order;

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	/**
	*The wrapper for the properties of the product attribute to set up or generate from the system in the product admin. Properties include namespace, attribute code, attribute sequence, site group ID, input type, value type, data type, boolean flags, and metadata key value pairs.
	*/
	@JsonProperty("AttributeDetail")
	protected Attribute attributeDetail;

	public Attribute getAttributeDetail() {
		return this.attributeDetail;
	}

	public void setAttributeDetail(Attribute attributeDetail) {
		this.attributeDetail = attributeDetail;
	}

	/**
	*The list of vocabulary values available for the attribute associated with the product type.
	*/
	@JsonProperty("VocabularyValues")
	protected ArrayList<AttributeVocabularyValueInProductType> vocabularyValues;
	public ArrayList<AttributeVocabularyValueInProductType> getVocabularyValues() {
		return this.vocabularyValues;
	}
	public void setVocabularyValues(ArrayList<AttributeVocabularyValueInProductType> vocabularyValues) {
		this.vocabularyValues = vocabularyValues;
	}

}
