/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.contracts.productadmin;

import java.io.Serializable;
import java.util.Date;
import com.mozu.api.contracts.productadmin.AttributeVocabularyValue;

public class AttributeVocabularyValueInProductType implements Serializable
{
	// Default Serial Version UID
	private static final long serialVersionUID = 1L;

	protected Integer order;

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	protected Object value;

	public Object getValue() {
		return this.value;
	}

	public void setValue(Object value) {
		this.value = value;
	}

	protected AttributeVocabularyValue vocabularyValueDetail;

	public AttributeVocabularyValue getVocabularyValueDetail() {
		return this.vocabularyValueDetail;
	}

	public void setVocabularyValueDetail(AttributeVocabularyValue vocabularyValueDetail) {
		this.vocabularyValueDetail = vocabularyValueDetail;
	}

}
