
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.productadmin;

import java.util.ArrayList;
import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mozu.api.contracts.productadmin.FacetSource;
import com.mozu.api.contracts.productadmin.Facet;


/**
*	The list of category, price, and attribute facets defined or available for definition for the category.
*/
public class FacetSet implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	/**
	*The list of subcategories and attributes that have not been defined as facets for the category.
	*/
	@JsonProperty("Available")
	protected ArrayList<FacetSource> available;
	public ArrayList<FacetSource> getAvailable() {
		return this.available;
	}
	public void setAvailable(ArrayList<FacetSource> available) {
		this.available = available;
	}

	/**
	*The list of category, price, and attribute facets defined for the category.
	*/
	@JsonProperty("Configured")
	protected ArrayList<Facet> configured;
	public ArrayList<Facet> getConfigured() {
		return this.configured;
	}
	public void setConfigured(ArrayList<Facet> configured) {
		this.configured = configured;
	}

}
