/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.urls.content;

import com.mozu.api.MozuUrl;
import com.mozu.api.utils.UrlFormatter;


public class PropertyTypeUrl
{

	/**
	 * Get Resource Url for GetList
	 * @param pageSize The number of results to display on each page when creating paged results from a query. The maximum value is 200.
	 * @param startIndex 
	 * @return   String Resource Url
	 */
	public static MozuUrl getListUrl(Integer pageSize, Integer startIndex)
	{
		UrlFormatter formatter = new UrlFormatter("/api/content/propertytypes/?pageSize={pageSize}&startIndex={startIndex}");
		formatter.formatUrl("pageSize", pageSize);
		formatter.formatUrl("startIndex", startIndex);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for Get
	 * @param propertyTypeName The name of the content property type.
	 * @return   String Resource Url
	 */
	public static MozuUrl getUrl(String propertyTypeName)
	{
		UrlFormatter formatter = new UrlFormatter("/api/content/propertytypes/{propertyTypeName}");
		formatter.formatUrl("propertyTypeName", propertyTypeName);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for PropertyValueTypes
	 * @return   String Resource Url
	 */
	public static MozuUrl propertyValueTypesUrl()
	{
		UrlFormatter formatter = new UrlFormatter("/api/content/propertytypes/propertyvaluetypes");
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

}

