/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.clients.content;

import java.util.List;
import java.util.ArrayList;
import com.mozu.api.MozuClient;
import com.mozu.api.MozuUrl;
import com.mozu.api.Headers;
import com.mozu.api.security.AuthTicket;

/** <summary>
 * Use the property types subresource to manage content properties.
 * </summary>
 */
public class PropertyTypeClient {
	
	/**
	 * Retrieves a list of the content property types.
	 * <p><pre><code>
	 * MozuClient<com.mozu.api.contracts.content.PropertyTypeCollection> mozuClient=GetListClient(dataViewMode);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * PropertyTypeCollection propertyTypeCollection = client.Result();
	 * </code></pre></p>
	 * @param authTicket User Auth Ticket
	 * @return Mozu.Api.MozuClient <com.mozu.api.contracts.content.PropertyTypeCollection>
	 * @see com.mozu.api.contracts.content.PropertyTypeCollection
	 */
	public static MozuClient<com.mozu.api.contracts.content.PropertyTypeCollection> getListClient(com.mozu.api.DataViewMode dataViewMode) throws Exception
	{
		return getListClient(dataViewMode,  null,  null, null);
	}

	/**
	 * Retrieves a list of the content property types.
	 * <p><pre><code>
	 * MozuClient<com.mozu.api.contracts.content.PropertyTypeCollection> mozuClient=GetListClient(dataViewMode,  pageSize,  startIndex, authTicket);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * PropertyTypeCollection propertyTypeCollection = client.Result();
	 * </code></pre></p>
	 * @param pageSize The number of results to display on each page when creating paged results from a query. The maximum value is 200.
	 * @param startIndex 
	 * @param authTicket User Auth Ticket
	 * @return Mozu.Api.MozuClient <com.mozu.api.contracts.content.PropertyTypeCollection>
	 * @see com.mozu.api.contracts.content.PropertyTypeCollection
	 */
	public static MozuClient<com.mozu.api.contracts.content.PropertyTypeCollection> getListClient(com.mozu.api.DataViewMode dataViewMode, Integer pageSize, Integer startIndex, AuthTicket authTicket) throws Exception
	{
		MozuUrl url = com.mozu.api.urls.content.PropertyTypeUrl.getListUrl(pageSize, startIndex);
		String verb = "GET";
		Class<?> clz = com.mozu.api.contracts.content.PropertyTypeCollection.class;
		MozuClient<com.mozu.api.contracts.content.PropertyTypeCollection> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.addHeader(Headers.X_VOL_DATAVIEW_MODE ,dataViewMode.toString());
		if (authTicket != null)
			mozuClient.setUserAuth(authTicket);
		return mozuClient;

	}

	/**
	 * Retrieves the details of the content property type.
	 * <p><pre><code>
	 * MozuClient<com.mozu.api.contracts.content.PropertyType> mozuClient=GetClient(dataViewMode,  propertyTypeName, authTicket);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * PropertyType propertyType = client.Result();
	 * </code></pre></p>
	 * @param propertyTypeName The name of the content property type.
	 * @param authTicket User Auth Ticket
	 * @return Mozu.Api.MozuClient <com.mozu.api.contracts.content.PropertyType>
	 * @see com.mozu.api.contracts.content.PropertyType
	 */
	public static MozuClient<com.mozu.api.contracts.content.PropertyType> getClient(com.mozu.api.DataViewMode dataViewMode, String propertyTypeName, AuthTicket authTicket) throws Exception
	{
		MozuUrl url = com.mozu.api.urls.content.PropertyTypeUrl.getUrl(propertyTypeName);
		String verb = "GET";
		Class<?> clz = com.mozu.api.contracts.content.PropertyType.class;
		MozuClient<com.mozu.api.contracts.content.PropertyType> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.addHeader(Headers.X_VOL_DATAVIEW_MODE ,dataViewMode.toString());
		if (authTicket != null)
			mozuClient.setUserAuth(authTicket);
		return mozuClient;

	}

	/**
	 * Retrieves the value types associated with a content property.
	 * <p><pre><code>
	 * MozuClient<List<com.mozu.api.contracts.content.PropertyValueType>> mozuClient=PropertyValueTypesClient(dataViewMode, authTicket);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * PropertyValueType propertyValueType = client.Result();
	 * </code></pre></p>
	 * @param authTicket User Auth Ticket
	 * @return Mozu.Api.MozuClient <List<com.mozu.api.contracts.content.PropertyValueType>>
	 * @see com.mozu.api.contracts.content.PropertyValueType
	 */
	public static MozuClient<List<com.mozu.api.contracts.content.PropertyValueType>> propertyValueTypesClient(com.mozu.api.DataViewMode dataViewMode, AuthTicket authTicket) throws Exception
	{
		MozuUrl url = com.mozu.api.urls.content.PropertyTypeUrl.propertyValueTypesUrl();
		String verb = "GET";
		Class<?> clz = new ArrayList<com.mozu.api.contracts.content.PropertyValueType>(){}.getClass();
		MozuClient<List<com.mozu.api.contracts.content.PropertyValueType>> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.addHeader(Headers.X_VOL_DATAVIEW_MODE ,dataViewMode.toString());
		if (authTicket != null)
			mozuClient.setUserAuth(authTicket);
		return mozuClient;

	}

}



