/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.resources.commerce.catalog.admin.attributedefinition.attributes;

import com.mozu.api.ApiContext;
import com.mozu.api.resources.BaseResource;
import java.util.ArrayList;
import com.mozu.api.MozuClient;

/// <summary>
/// Vocabulary values are predefined for an attribute.
/// </summary>
public class AttributeVocabularyValueResource extends BaseResource {
	///
	/// <see cref="Mozu.Api.ApiContext"/>
	///
	private ApiContext _apiContext;
	
	public AttributeVocabularyValueResource(ApiContext apiContext) 
	{
		_apiContext = apiContext;
	}
	
	/**
	* Retrieves a list of attribute vocabulary values. To target a query, use one or several valid optional response groups.
	* <p><pre><code>
	*    AttributeVocabularyValue attributevocabularyvalue = new AttributeVocabularyValue();
	*   AttributeVocabularyValue attributeVocabularyValue = attributevocabularyvalue.GetAttributeVocabularyValues( attributeFQN);
	* </code></pre></p>
	* @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
	* @return List<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	*/
	public ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> getAttributeVocabularyValues(String attributeFQN) throws Exception
	{
		MozuClient<ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>> client = com.mozu.api.clients.commerce.catalog.admin.attributedefinition.attributes.AttributeVocabularyValueClient.getAttributeVocabularyValuesClient( attributeFQN);
		setContext(_apiContext, client,true);
		client.executeRequest();
		return client.getResult();

	}

/**
	* Retrieves an attribute vocabulary value by providing the attribute FQN and value.
	* <p><pre><code>
	*    AttributeVocabularyValue attributevocabularyvalue = new AttributeVocabularyValue();
	*   AttributeVocabularyValue attributeVocabularyValue = attributevocabularyvalue.GetAttributeVocabularyValue( attributeFQN,  value);
	* </code></pre></p>
	* @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
	* @param value The actual unique value of the attribute vocabulary to retrieve. A single attribute must have a unique value and match the attribute's data type. If a string value returns null, the system will generate a value. The actual string content displayed shoud be stored as "Content" and actual content is required for string values.
	* @return com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	*/
	public com.mozu.api.contracts.productadmin.AttributeVocabularyValue getAttributeVocabularyValue(String attributeFQN, String value) throws Exception
	{
		MozuClient<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> client = com.mozu.api.clients.commerce.catalog.admin.attributedefinition.attributes.AttributeVocabularyValueClient.getAttributeVocabularyValueClient( attributeFQN,  value);
		setContext(_apiContext, client,true);
		client.executeRequest();
		return client.getResult();

	}

	/**
	* Adds a new attribute vocabulary value.
	* <p><pre><code>
	*    AttributeVocabularyValue attributevocabularyvalue = new AttributeVocabularyValue();
	*   AttributeVocabularyValue attributeVocabularyValue = attributevocabularyvalue.AddAttributeVocabularyValue( attributeFQN,  attributeVocabularyValue);
	* </code></pre></p>
	* @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
	* @param attributeVocabularyValue The predefined vocabulary value to add to the attribute content.
	* @return com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	*/
	public com.mozu.api.contracts.productadmin.AttributeVocabularyValue addAttributeVocabularyValue(String attributeFQN, com.mozu.api.contracts.productadmin.AttributeVocabularyValue attributeVocabularyValue) throws Exception
	{
		MozuClient<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> client = com.mozu.api.clients.commerce.catalog.admin.attributedefinition.attributes.AttributeVocabularyValueClient.addAttributeVocabularyValueClient( attributeFQN,  attributeVocabularyValue);
		setContext(_apiContext, client,true);
		client.executeRequest();
		return client.getResult();

	}

	/**
	* Update existing vocabulary values for an attribute.
	* <p><pre><code>
	*    AttributeVocabularyValue attributevocabularyvalue = new AttributeVocabularyValue();
	*   AttributeVocabularyValue attributeVocabularyValue = attributevocabularyvalue.UpdateAttributeVocabularyValues( attributeFQN,  vocabularyValues);
	* </code></pre></p>
	* @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
	* @param vocabularyValues The actual vocabulary values for the attribute being updated.
	* @return List<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	*/
	public ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> updateAttributeVocabularyValues(String attributeFQN, ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> vocabularyValues) throws Exception
	{
		MozuClient<ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>> client = com.mozu.api.clients.commerce.catalog.admin.attributedefinition.attributes.AttributeVocabularyValueClient.updateAttributeVocabularyValuesClient( attributeFQN,  vocabularyValues);
		setContext(_apiContext, client,true);
		client.executeRequest();
		return client.getResult();

	}

/**
	* Updates existing attribute vocabulary values.
	* <p><pre><code>
	*    AttributeVocabularyValue attributevocabularyvalue = new AttributeVocabularyValue();
	*   AttributeVocabularyValue attributeVocabularyValue = attributevocabularyvalue.UpdateAttributeVocabularyValue( attributeFQN,  value,  attributeVocabularyValue);
	* </code></pre></p>
	* @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
	* @param value The actual unique value of the attribute vocabulary value to update. A single attribute must have a unique value and match the attribute's data type. If a string value returns null, the system will generate a value. The actual string content displayed shoud be stored as "Content" and actual content is required for string values.
	* @param attributeVocabularyValue The predefined vocabulary value to add to the attribute content to update.
	* @return com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	*/
	public com.mozu.api.contracts.productadmin.AttributeVocabularyValue updateAttributeVocabularyValue(String attributeFQN, String value, com.mozu.api.contracts.productadmin.AttributeVocabularyValue attributeVocabularyValue) throws Exception
	{
		MozuClient<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> client = com.mozu.api.clients.commerce.catalog.admin.attributedefinition.attributes.AttributeVocabularyValueClient.updateAttributeVocabularyValueClient( attributeFQN,  value,  attributeVocabularyValue);
		setContext(_apiContext, client,true);
		client.executeRequest();
		return client.getResult();

	}

	/**
	* Deletes an attribute's vocabulary value.
	* <p><pre><code>
	*    AttributeVocabularyValue attributevocabularyvalue = new AttributeVocabularyValue();
	*   attributevocabularyvalue.DeleteAttributeVocabularyValue( attributeFQN,  value);
	* </code></pre></p>
	* @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
	* @param value The actual unique value of the attribute vocabulary to delete. A single attribute must have a unique value and match the attribute's data type. If a string value returns null, the system will generate a value. The actual string content displayed shoud be stored as "Content" and actual content is required for string values.
	* @return 
	*/
	public void deleteAttributeVocabularyValue(String attributeFQN, String value) throws Exception
	{
		MozuClient client = com.mozu.api.clients.commerce.catalog.admin.attributedefinition.attributes.AttributeVocabularyValueClient.deleteAttributeVocabularyValueClient( attributeFQN,  value);
		setContext(_apiContext, client,true);
		client.executeRequest();

	}


}



