/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.resources.content.documentlists;

import com.mozu.api.ApiContext;
import java.util.List;
import java.util.ArrayList;
import com.mozu.api.MozuClient;
import com.mozu.api.MozuUrl;
import com.mozu.api.Headers;
import com.mozu.api.security.AuthTicket;

/** <summary>
 * 
 * </summary>
 */
public class FacetResource {
	///
	/// <see cref="Mozu.Api.ApiContext"/>
	///
	private ApiContext _apiContext;
	public FacetResource(ApiContext apiContext) 
	{
		_apiContext = apiContext;
	}
	
	/**
	 * 
	 * <p><pre><code>
	 *	Facet facet = new Facet();
	 *	Facet facet = facet.GetFacets( documentListName,  propertyName, authTicket);
	 * </code></pre></p>
	 * @param documentListName 
	 * @param propertyName 
	 * @param authTicket User Auth Ticket
	 * @return List<com.mozu.api.contracts.content.Facet>
	 * @see com.mozu.api.contracts.content.Facet
	 */
	public List<com.mozu.api.contracts.content.Facet> getFacets(String documentListName, String propertyName, AuthTicket authTicket) throws Exception
	{
		MozuClient<List<com.mozu.api.contracts.content.Facet>> client = com.mozu.api.clients.content.documentlists.FacetClient.getFacetsClient( documentListName,  propertyName, authTicket);
		client.setContext(_apiContext);
		client.executeRequest();
		return client.getResult();

	}

}



