/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.urls.commerce.orders;

import com.mozu.api.MozuUrl;
import com.mozu.api.utils.UrlFormatter;


public class ShipmentUrl
{

	/**
	 * Get Resource Url for GetShipment
	 * @param orderId 
	 * @param shipmentId 
	 * @return   String Resource Url
	 */
	public static MozuUrl getShipmentUrl(String orderId, String shipmentId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/orders/{orderId}/shipments/{shipmentId}");
		formatter.formatUrl("orderId", orderId);
		formatter.formatUrl("shipmentId", shipmentId);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for GetAvailableShipmentMethods
	 * @param orderId 
	 * @return   String Resource Url
	 */
	public static MozuUrl getAvailableShipmentMethodsUrl(String orderId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/orders/{orderId}/shipments/methods");
		formatter.formatUrl("orderId", orderId);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for CreatePackageShipments
	 * @param orderId 
	 * @return   String Resource Url
	 */
	public static MozuUrl createPackageShipmentsUrl(String orderId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/orders/{orderId}/shipments");
		formatter.formatUrl("orderId", orderId);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for DeleteShipment
	 * @param orderId 
	 * @param shipmentId 
	 * @return   String Resource Url
	 */
	public static MozuUrl deleteShipmentUrl(String orderId, String shipmentId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/orders/{orderId}/shipments/{shipmentId}");
		formatter.formatUrl("orderId", orderId);
		formatter.formatUrl("shipmentId", shipmentId);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

}

