
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.commerceruntime.commerce;

import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;


/**
*	Properties of an ad-hoc price adjustment for an order.
*/
public class Adjustment implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	/**
	*The amount of the order-level adjustment, which can be a positive or negative amount.
	*/
	@JsonProperty("Amount")
	protected Double amount;

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	*The shopper-facing description of the order-level adjustment.
	*/
	@JsonProperty("Description")
	protected String description;

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/**
	*Administrator notes associated with the order adjustment. These comments are not shopper facing.
	*/
	@JsonProperty("InternalComment")
	protected String internalComment;

	public String getInternalComment() {
		return this.internalComment;
	}

	public void setInternalComment(String internalComment) {
		this.internalComment = internalComment;
	}

}
