/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.contracts.commerceruntime.commerce;

import java.io.Serializable;
import java.util.Date;

public class CommerceUnitPrice implements Serializable
{
	// Default Serial Version UID
	private static final long serialVersionUID = 1L;

	protected Double baseAmount;

	public Double getBaseAmount() {
		return this.baseAmount;
	}

	public void setBaseAmount(Double baseAmount) {
		this.baseAmount = baseAmount;
	}

	protected Double discountAmount;

	public Double getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(Double discountAmount) {
		this.discountAmount = discountAmount;
	}

	protected Double discountedAmount;

	public Double getDiscountedAmount() {
		return this.discountedAmount;
	}

	public void setDiscountedAmount(Double discountedAmount) {
		this.discountedAmount = discountedAmount;
	}

	protected Double extendedAmount;

	public Double getExtendedAmount() {
		return this.extendedAmount;
	}

	public void setExtendedAmount(Double extendedAmount) {
		this.extendedAmount = extendedAmount;
	}

	protected Double listAmount;

	public Double getListAmount() {
		return this.listAmount;
	}

	public void setListAmount(Double listAmount) {
		this.listAmount = listAmount;
	}

	protected Double overrideAmount;

	public Double getOverrideAmount() {
		return this.overrideAmount;
	}

	public void setOverrideAmount(Double overrideAmount) {
		this.overrideAmount = overrideAmount;
	}

	protected Double saleAmount;

	public Double getSaleAmount() {
		return this.saleAmount;
	}

	public void setSaleAmount(Double saleAmount) {
		this.saleAmount = saleAmount;
	}

}
