
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.urls.commerce.customer.accounts;

import com.mozu.api.utils.UrlFormatter;


public class CardUrl
{

	/**
        * Get Resource Url for GetAccountCards
        * @param accountId Unique identifier of the customer account.
        * @return    String Resource Url
    */
	public static String getAccountCardsUrl(Integer accountId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/customer/accounts/{accountId}/cards");
		formatter.formatUrl("accountId", accountId);
		return formatter.getResourceUrl();
	}

		/**
        * Get Resource Url for AddAccountCard
        * @param accountId Unique identifier of the customer account.
        * @return    String Resource Url
    */
	public static String addAccountCardUrl(Integer accountId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/customer/accounts/{accountId}/cards");
		formatter.formatUrl("accountId", accountId);
		return formatter.getResourceUrl();
	}

		/**
        * Get Resource Url for UpdateAccountCard
        * @param accountId Unique identifier of the customer account.
        * @return    String Resource Url
    */
	public static String updateAccountCardUrl(Integer accountId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/customer/accounts/{accountId}/cards");
		formatter.formatUrl("accountId", accountId);
		return formatter.getResourceUrl();
	}

		/**
        * Get Resource Url for DeleteAccountCard
        * @param accountId Unique identifier of the customer account.
        * @param cardId Unique identifier of the credit card to delete.
        * @return    String Resource Url
    */
	public static String deleteAccountCardUrl(Integer accountId, String cardId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/customer/accounts/{accountId}/cards/{cardId}");
		formatter.formatUrl("accountId", accountId);
		formatter.formatUrl("cardId", cardId);
		return formatter.getResourceUrl();
	}

	
}

