
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.productruntime;

import java.util.ArrayList;
import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mozu.api.contracts.productruntime.Category;
import com.mozu.api.contracts.productruntime.ProductImage;
import com.mozu.api.contracts.productruntime.PackageMeasurements;
import com.mozu.api.contracts.productruntime.ProductPrice;
import com.mozu.api.contracts.productruntime.ProductProperty;
import com.mozu.api.contracts.productruntime.ProductPurchasableState;
import com.mozu.api.contracts.productruntime.ProductStock;


/**
*	Summary list of the product validation in a storefront, including options selected by the shopper.
*/
public class ProductValidationSummary implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	/**
	*If true, the entity is subject to tax based on the relevant tax rate.
	*/
	@JsonProperty("IsTaxable")
	protected Boolean isTaxable;

	public Boolean getIsTaxable() {
		return this.isTaxable;
	}

	public void setIsTaxable(Boolean isTaxable) {
		this.isTaxable = isTaxable;
	}

	/**
	*Merchant-created code that uniquely identifies the product such as a SKU or item number. Once created, the product code is read-only.
	*/
	@JsonProperty("ProductCode")
	protected String productCode;

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	/**
	*The descriptive brief product name.
	*/
	@JsonProperty("ProductName")
	protected String productName;

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	*Brief description of the product typically used when the product is displayed in a list or in search results.
	*/
	@JsonProperty("ProductShortDescription")
	protected String productShortDescription;

	public String getProductShortDescription() {
		return this.productShortDescription;
	}

	public void setProductShortDescription(String productShortDescription) {
		this.productShortDescription = productShortDescription;
	}

	/**
	*Merchant-created code associated with a specific product variation. Variation product codes maintain an association with the base product code.
	*/
	@JsonProperty("VariationProductCode")
	protected String variationProductCode;

	public String getVariationProductCode() {
		return this.variationProductCode;
	}

	public void setVariationProductCode(String variationProductCode) {
		this.variationProductCode = variationProductCode;
	}

	/**
	*The list of product categories for the storefront.
	*/
	@JsonProperty("Categories")
	protected ArrayList<Category> categories;
	public ArrayList<Category> getCategories() {
		return this.categories;
	}
	public void setCategories(ArrayList<Category> categories) {
		this.categories = categories;
	}

	/**
	*The image configured for the product on the storefront.
	*/
	@JsonProperty("Image")
	protected ProductImage image;

	public ProductImage getImage() {
		return this.image;
	}

	public void setImage(ProductImage image) {
		this.image = image;
	}

	/**
	*Dimensions of the packaged product.
	*/
	@JsonProperty("Measurements")
	protected PackageMeasurements measurements;

	public PackageMeasurements getMeasurements() {
		return this.measurements;
	}

	public void setMeasurements(PackageMeasurements measurements) {
		this.measurements = measurements;
	}

	/**
	*Price that the merchant intends to sell the product which is not necessarily the list price. This is the price the merchant intends to sell the product if no sale price is present.
	*/
	@JsonProperty("Price")
	protected ProductPrice price;

	public ProductPrice getPrice() {
		return this.price;
	}

	public void setPrice(ProductPrice price) {
		this.price = price;
	}

	/**
	*The list of product properties configured in product admin.
	*/
	@JsonProperty("Properties")
	protected ArrayList<ProductProperty> properties;
	public ArrayList<ProductProperty> getProperties() {
		return this.properties;
	}
	public void setProperties(ArrayList<ProductProperty> properties) {
		this.properties = properties;
	}

	/**
	*The current state of the product and whether or not it is available for purchasing. If the product is not eligible for purchase, the validation message is included.
	*/
	@JsonProperty("PurchasableState")
	protected ProductPurchasableState purchasableState;

	public ProductPurchasableState getPurchasableState() {
		return this.purchasableState;
	}

	public void setPurchasableState(ProductPurchasableState purchasableState) {
		this.purchasableState = purchasableState;
	}

	/**
	*The number of products accounted for in inventory that are available for purchase.
	*/
	@JsonProperty("Stock")
	protected ProductStock stock;

	public ProductStock getStock() {
		return this.stock;
	}

	public void setStock(ProductStock stock) {
		this.stock = stock;
	}

}
