
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.commerceruntime.payments;

import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mozu.api.contracts.commerceruntime.payments.Payment;


/**
*	Collection of payment transactions associated with an order.
*/
public class PaymentCollection implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	/**
	*The maximum number of items that can appear in this collection.
	*/
	@JsonProperty("Capacity")
	protected Integer capacity;

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	/**
	*The number of results listed in the query collection, represented by a signed 64-bit (8-byte) integer. This value is system-supplied and read-only.
	*/
	@JsonProperty("Count")
	protected Integer count;

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	*An array list of objects in the returned collection.
	*/
	@JsonProperty("Item")
	protected Payment item;

	public Payment getItem() {
		return this.item;
	}

	public void setItem(Payment item) {
		this.item = item;
	}

}
