/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.clients.commerce.catalog.admin;

import java.util.ArrayList;
import com.mozu.api.MozuClient;

/// <summary>
/// 
/// </summary>
public class SiteGroupClient {
	
	
	/**
	* 
	* <p><pre><code>
	*   MozuClient<com.mozu.api.contracts.productadmin.SiteGroupCollection> mozuClient=GetSiteGroupsClient();
	* client.setBaseAddress(url);
	* client.executeRequest();
	* SiteGroupCollection siteGroupCollection = client.Result();
	* </code></pre></p>
	* @return Mozu.Api.MozuClient <com.mozu.api.contracts.productadmin.SiteGroupCollection>
	* @see com.mozu.api.contracts.productadmin.SiteGroupCollection
	*/
	public static MozuClient<com.mozu.api.contracts.productadmin.SiteGroupCollection> getSiteGroupsClient() throws Exception
	{
		return getSiteGroupsClient( null,  null);
	}

/**
	* 
	* <p><pre><code>
	*   MozuClient<com.mozu.api.contracts.productadmin.SiteGroupCollection> mozuClient=GetSiteGroupsClient( pageSize,  startIndex);
	* client.setBaseAddress(url);
	* client.executeRequest();
	* SiteGroupCollection siteGroupCollection = client.Result();
	* </code></pre></p>
	* @param pageSize 
	* @param startIndex 
	* @return Mozu.Api.MozuClient <com.mozu.api.contracts.productadmin.SiteGroupCollection>
	* @see com.mozu.api.contracts.productadmin.SiteGroupCollection
	*/
	public static MozuClient<com.mozu.api.contracts.productadmin.SiteGroupCollection> getSiteGroupsClient(Integer pageSize, Integer startIndex) throws Exception
	{
		String url = com.mozu.api.urls.commerce.catalog.admin.SiteGroupUrl.getSiteGroupsUrl(pageSize, startIndex);
		String verb = "GET";
		Class<?> clz = com.mozu.api.contracts.productadmin.SiteGroupCollection.class;
		MozuClient<com.mozu.api.contracts.productadmin.SiteGroupCollection> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		return mozuClient;

	}

/**
	* 
	* <p><pre><code>
	*   MozuClient<com.mozu.api.contracts.productadmin.SiteGroup> mozuClient=GetSiteGroupClient( siteGroupId);
	* client.setBaseAddress(url);
	* client.executeRequest();
	* SiteGroup siteGroup = client.Result();
	* </code></pre></p>
	* @param siteGroupId 
	* @return Mozu.Api.MozuClient <com.mozu.api.contracts.productadmin.SiteGroup>
	* @see com.mozu.api.contracts.productadmin.SiteGroup
	*/
	public static MozuClient<com.mozu.api.contracts.productadmin.SiteGroup> getSiteGroupClient(Integer siteGroupId) throws Exception
	{
		String url = com.mozu.api.urls.commerce.catalog.admin.SiteGroupUrl.getSiteGroupUrl(siteGroupId);
		String verb = "GET";
		Class<?> clz = com.mozu.api.contracts.productadmin.SiteGroup.class;
		MozuClient<com.mozu.api.contracts.productadmin.SiteGroup> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		return mozuClient;

	}

		/**
	* 
	* <p><pre><code>
	*   MozuClient<com.mozu.api.contracts.productadmin.SiteGroup> mozuClient=UpdateSiteGroupClient( siteGroupId,  siteGroup);
	* client.setBaseAddress(url);
	* client.executeRequest();
	* SiteGroup siteGroup = client.Result();
	* </code></pre></p>
	* @param siteGroupId 
	* @param siteGroup 
	* @return Mozu.Api.MozuClient <com.mozu.api.contracts.productadmin.SiteGroup>
	* @see com.mozu.api.contracts.productadmin.SiteGroup
	* @see com.mozu.api.contracts.productadmin.SiteGroup
	*/
	public static MozuClient<com.mozu.api.contracts.productadmin.SiteGroup> updateSiteGroupClient(Integer siteGroupId, com.mozu.api.contracts.productadmin.SiteGroup siteGroup) throws Exception
	{
		String url = com.mozu.api.urls.commerce.catalog.admin.SiteGroupUrl.updateSiteGroupUrl(siteGroupId);
		String verb = "PUT";
		Class<?> clz = com.mozu.api.contracts.productadmin.SiteGroup.class;
		MozuClient<com.mozu.api.contracts.productadmin.SiteGroup> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.setBody(siteGroup);
		return mozuClient;

	}

	
}



