/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.clients.commerce.settings.shipping;

import java.util.ArrayList;
import com.mozu.api.MozuClient;

/// <summary>
/// Use the active rate providers subresource to manage entities that provide estimated shipping rate calculations. Active rate providers represent carrier configurations set up in the shipping admin service.
/// </summary>
public class FeatureClient {
	
	
	/**
	* Retrieves a list of the active rate providers configured for the site.
	* <p><pre><code>
	*   MozuClient<ArrayList<com.mozu.api.contracts.core.Feature>> mozuClient=GetActiveRateProvidersClient();
	* client.setBaseAddress(url);
	* client.executeRequest();
	* Feature feature = client.Result();
	* </code></pre></p>
	* @return Mozu.Api.MozuClient <List<com.mozu.api.contracts.core.Feature>>
	* @see com.mozu.api.contracts.core.Feature
	*/
	public static MozuClient<ArrayList<com.mozu.api.contracts.core.Feature>> getActiveRateProvidersClient() throws Exception
	{
		String url = com.mozu.api.urls.commerce.settings.shipping.FeatureUrl.getActiveRateProvidersUrl();
		String verb = "GET";
		Class<?> clz = new ArrayList<com.mozu.api.contracts.core.Feature>(){}.getClass();
		MozuClient<ArrayList<com.mozu.api.contracts.core.Feature>> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		return mozuClient;

	}

	/**
	* Creates a new active rate provider for the site.
	* <p><pre><code>
	*   MozuClient<com.mozu.api.contracts.core.Feature> mozuClient=AddActiveRateProviderClient( activeRateProvider);
	* client.setBaseAddress(url);
	* client.executeRequest();
	* Feature feature = client.Result();
	* </code></pre></p>
	* @param activeRateProvider Properties of the active rate provider to create.
	* @return Mozu.Api.MozuClient <com.mozu.api.contracts.core.Feature>
	* @see com.mozu.api.contracts.core.Feature
	* @see com.mozu.api.contracts.core.Feature
	*/
	public static MozuClient<com.mozu.api.contracts.core.Feature> addActiveRateProviderClient(com.mozu.api.contracts.core.Feature activeRateProvider) throws Exception
	{
		String url = com.mozu.api.urls.commerce.settings.shipping.FeatureUrl.addActiveRateProviderUrl();
		String verb = "POST";
		Class<?> clz = com.mozu.api.contracts.core.Feature.class;
		MozuClient<com.mozu.api.contracts.core.Feature> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.setBody(activeRateProvider);
		return mozuClient;

	}

	/**
	* Updates the active rate providers configured for the site.
	* <p><pre><code>
	*   MozuClient<ArrayList<com.mozu.api.contracts.core.Feature>> mozuClient=UpdateActiveRateProvidersClient( activeRateProviders);
	* client.setBaseAddress(url);
	* client.executeRequest();
	* Feature feature = client.Result();
	* </code></pre></p>
	* @param activeRateProviders Properties of the active rate provider to update.
	* @return Mozu.Api.MozuClient <List<com.mozu.api.contracts.core.Feature>>
	* @see com.mozu.api.contracts.core.Feature
	* @see com.mozu.api.contracts.core.Feature
	*/
	public static MozuClient<ArrayList<com.mozu.api.contracts.core.Feature>> updateActiveRateProvidersClient(ArrayList<com.mozu.api.contracts.core.Feature> activeRateProviders) throws Exception
	{
		String url = com.mozu.api.urls.commerce.settings.shipping.FeatureUrl.updateActiveRateProvidersUrl();
		String verb = "PUT";
		Class<?> clz = new ArrayList<com.mozu.api.contracts.core.Feature>(){}.getClass();
		MozuClient<ArrayList<com.mozu.api.contracts.core.Feature>> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.setBody(activeRateProviders);
		return mozuClient;

	}

	
}



