
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.core.extensible;

import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mozu.api.contracts.core.extensible.Attribute;


/**
*	Properties for an attribute set attribute.
*/
public class AttributeSetAttribute implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	/**
	*If true, the attribute in the attribute set has multiple values.
	*/
	@JsonProperty("IsMultiValued")
	protected Boolean isMultiValued;

	public Boolean getIsMultiValued() {
		return this.isMultiValued;
	}

	public void setIsMultiValued(Boolean isMultiValued) {
		this.isMultiValued = isMultiValued;
	}

	/**
	*If true, the attribute in the attribute set is read-only and cannot be modified.
	*/
	@JsonProperty("IsReadOnly")
	protected Boolean isReadOnly;

	public Boolean getIsReadOnly() {
		return this.isReadOnly;
	}

	public void setIsReadOnly(Boolean isReadOnly) {
		this.isReadOnly = isReadOnly;
	}

	/**
	*If true, the entity is required for the request to return a valid response.
	*/
	@JsonProperty("IsRequired")
	protected Boolean isRequired;

	public Boolean getIsRequired() {
		return this.isRequired;
	}

	public void setIsRequired(Boolean isRequired) {
		this.isRequired = isRequired;
	}

	/**
	*The numeric value that denotes the place this entity occupies in the order of the entity list.
	*/
	@JsonProperty("Sequence")
	protected Integer sequence;

	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	/**
	*Wrapper for the attribute properties to extend.
	*/
	@JsonProperty("Attribute")
	protected Attribute attribute;

	public Attribute getAttribute() {
		return this.attribute;
	}

	public void setAttribute(Attribute attribute) {
		this.attribute = attribute;
	}

}
