
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.shippingruntime;

import java.util.ArrayList;
import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mozu.api.contracts.shippingruntime.CustomAttribute;


public class CustomAttribute implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	@JsonProperty("Key")
	protected String key;

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@JsonProperty("Value")
	protected String value;

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@JsonProperty("ChildAttributes")
	protected ArrayList<CustomAttribute> childAttributes;
	public ArrayList<CustomAttribute> getChildAttributes() {
		return this.childAttributes;
	}
	public void setChildAttributes(ArrayList<CustomAttribute> childAttributes) {
		this.childAttributes = childAttributes;
	}

}
