
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.shippingruntime;

import java.util.ArrayList;
import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mozu.api.contracts.shippingruntime.CustomAttribute;
import com.mozu.api.contracts.shippingruntime.Shipment;


public class ShipmentRequest implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	@JsonProperty("CarrierId")
	protected String carrierId;

	public String getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(String carrierId) {
		this.carrierId = carrierId;
	}

	@JsonProperty("ISOCurrencyCode")
	protected String iSOCurrencyCode;

	public String getISOCurrencyCode() {
		return this.iSOCurrencyCode;
	}

	public void setISOCurrencyCode(String iSOCurrencyCode) {
		this.iSOCurrencyCode = iSOCurrencyCode;
	}

	@JsonProperty("RequiresSignature")
	protected Boolean requiresSignature;

	public Boolean getRequiresSignature() {
		return this.requiresSignature;
	}

	public void setRequiresSignature(Boolean requiresSignature) {
		this.requiresSignature = requiresSignature;
	}

	@JsonProperty("ShipmentRequestType")
	protected String shipmentRequestType;

	public String getShipmentRequestType() {
		return this.shipmentRequestType;
	}

	public void setShipmentRequestType(String shipmentRequestType) {
		this.shipmentRequestType = shipmentRequestType;
	}

	@JsonProperty("ShippingServiceType")
	protected String shippingServiceType;

	public String getShippingServiceType() {
		return this.shippingServiceType;
	}

	public void setShippingServiceType(String shippingServiceType) {
		this.shippingServiceType = shippingServiceType;
	}

	@JsonProperty("CustomAttributes")
	protected ArrayList<CustomAttribute> customAttributes;
	public ArrayList<CustomAttribute> getCustomAttributes() {
		return this.customAttributes;
	}
	public void setCustomAttributes(ArrayList<CustomAttribute> customAttributes) {
		this.customAttributes = customAttributes;
	}

	@JsonProperty("Shipment")
	protected Shipment shipment;

	public Shipment getShipment() {
		return this.shipment;
	}

	public void setShipment(Shipment shipment) {
		this.shipment = shipment;
	}

}
