
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.shippingruntime;

import java.util.ArrayList;
import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mozu.api.contracts.shippingruntime.CustomAttribute;
import com.mozu.api.contracts.core.Contact;
import com.mozu.api.contracts.shippingruntime.Package;


public class Shipment implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	@JsonProperty("OrderTotal")
	protected Double orderTotal;

	public Double getOrderTotal() {
		return this.orderTotal;
	}

	public void setOrderTotal(Double orderTotal) {
		this.orderTotal = orderTotal;
	}

	@JsonProperty("ShippingMethodCodes")
	protected ArrayList<String> shippingMethodCodes;
	public ArrayList<String> getShippingMethodCodes() {
		return this.shippingMethodCodes;
	}
	public void setShippingMethodCodes(ArrayList<String> shippingMethodCodes) {
		this.shippingMethodCodes = shippingMethodCodes;
	}

	@JsonProperty("CustomAttributes")
	protected ArrayList<CustomAttribute> customAttributes;
	public ArrayList<CustomAttribute> getCustomAttributes() {
		return this.customAttributes;
	}
	public void setCustomAttributes(ArrayList<CustomAttribute> customAttributes) {
		this.customAttributes = customAttributes;
	}

	@JsonProperty("Destination")
	protected Contact destination;

	public Contact getDestination() {
		return this.destination;
	}

	public void setDestination(Contact destination) {
		this.destination = destination;
	}

	@JsonProperty("Origin")
	protected Contact origin;

	public Contact getOrigin() {
		return this.origin;
	}

	public void setOrigin(Contact origin) {
		this.origin = origin;
	}

	@JsonProperty("Packages")
	protected ArrayList<Package> packages;
	public ArrayList<Package> getPackages() {
		return this.packages;
	}
	public void setPackages(ArrayList<Package> packages) {
		this.packages = packages;
	}

}
