/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.urls.platform.user;

import com.mozu.api.MozuUrl;
import com.mozu.api.utils.UrlFormatter;


public class UserAuthTicketUrl
{

	/**
	 * Get Resource Url for CreateUserAuthTicket
	 * @return   String Resource Url
	 */
	public static MozuUrl createUserAuthTicketUrl()
	{
		UrlFormatter formatter = new UrlFormatter("/api/platform/user/userauthtickets/");
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for CreateAuthTicketForSite
	 * @return   String Resource Url
	 */
	public static MozuUrl createAuthTicketForSiteUrl()
	{
		UrlFormatter formatter = new UrlFormatter("/api/platform/user/userauthtickets/site");
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for RefreshUserAuthTicket
	 * @param refreshToken 
	 * @return   String Resource Url
	 */
	public static MozuUrl refreshUserAuthTicketUrl(String refreshToken)
	{
		UrlFormatter formatter = new UrlFormatter("/api/platform/user/userauthtickets/refresh?refreshToken={refreshToken}");
		formatter.formatUrl("refreshToken", refreshToken);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

}

