/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.resources.commerce.customer;

import com.mozu.api.ApiContext;
import com.mozu.api.resources.BaseResource;
import java.util.ArrayList;
import com.mozu.api.MozuClient;

/// <summary>
/// 
/// </summary>
public class VisitResource extends BaseResource {
	///
	/// <see cref="Mozu.Api.ApiContext"/>
	///
	private ApiContext _apiContext;
	
	public VisitResource(ApiContext apiContext) 
	{
		_apiContext = apiContext;
	}
	
		/**
	* 
	* <p><pre><code>
	*    Visit visit = new Visit();
	*   Visit visit = visit.AddVisit( visit);
	* </code></pre></p>
	* @param visit 
	* @return com.mozu.api.contracts.customer.Visit
	* @see com.mozu.api.contracts.customer.Visit
	* @see com.mozu.api.contracts.customer.Visit
	*/
	public com.mozu.api.contracts.customer.Visit addVisit(com.mozu.api.contracts.customer.Visit visit) throws Exception
	{
		MozuClient<com.mozu.api.contracts.customer.Visit> client = com.mozu.api.clients.commerce.customer.VisitClient.addVisitClient( visit);
		setContext(_apiContext, client,true);
		client.executeRequest();
		return client.getResult();

	}

/**
	* 
	* <p><pre><code>
	*    Visit visit = new Visit();
	*   Transaction transaction = visit.AddTransactionToVisit( visitId,  transaction);
	* </code></pre></p>
	* @param visitId 
	* @param transaction 
	* @return com.mozu.api.contracts.customer.Transaction
	* @see com.mozu.api.contracts.customer.Transaction
	* @see com.mozu.api.contracts.customer.Transaction
	*/
	public com.mozu.api.contracts.customer.Transaction addTransactionToVisit(String visitId, com.mozu.api.contracts.customer.Transaction transaction) throws Exception
	{
		MozuClient<com.mozu.api.contracts.customer.Transaction> client = com.mozu.api.clients.commerce.customer.VisitClient.addTransactionToVisitClient( visitId,  transaction);
		setContext(_apiContext, client,true);
		client.executeRequest();
		return client.getResult();

	}

	/**
	* 
	* <p><pre><code>
	*    Visit visit = new Visit();
	*   Visit visit = visit.UpdateVisit( visitId,  visit);
	* </code></pre></p>
	* @param visitId 
	* @param visit 
	* @return com.mozu.api.contracts.customer.Visit
	* @see com.mozu.api.contracts.customer.Visit
	* @see com.mozu.api.contracts.customer.Visit
	*/
	public com.mozu.api.contracts.customer.Visit updateVisit(String visitId, com.mozu.api.contracts.customer.Visit visit) throws Exception
	{
		MozuClient<com.mozu.api.contracts.customer.Visit> client = com.mozu.api.clients.commerce.customer.VisitClient.updateVisitClient( visitId,  visit);
		setContext(_apiContext, client,true);
		client.executeRequest();
		return client.getResult();

	}

/**
	* 
	* <p><pre><code>
	*    Visit visit = new Visit();
	*   Visit visit = visit.GetVisit( visitId);
	* </code></pre></p>
	* @param visitId 
	* @return com.mozu.api.contracts.customer.Visit
	* @see com.mozu.api.contracts.customer.Visit
	*/
	public com.mozu.api.contracts.customer.Visit getVisit(String visitId) throws Exception
	{
		MozuClient<com.mozu.api.contracts.customer.Visit> client = com.mozu.api.clients.commerce.customer.VisitClient.getVisitClient( visitId);
		setContext(_apiContext, client,true);
		client.executeRequest();
		return client.getResult();

	}

/**
	* 
	* <p><pre><code>
	*    Visit visit = new Visit();
	*   VisitCollection visitCollection = visit.GetVisits();
	* </code></pre></p>
	* @return com.mozu.api.contracts.customer.VisitCollection
	* @see com.mozu.api.contracts.customer.VisitCollection
	*/
	public com.mozu.api.contracts.customer.VisitCollection getVisits() throws Exception
	{
		return getVisits( null,  null,  null,  null);
	}

/**
	* 
	* <p><pre><code>
	*    Visit visit = new Visit();
	*   VisitCollection visitCollection = visit.GetVisits( filter,  pageSize,  sortBy,  startIndex);
	* </code></pre></p>
	* @param filter 
	* @param pageSize 
	* @param sortBy 
	* @param startIndex 
	* @return com.mozu.api.contracts.customer.VisitCollection
	* @see com.mozu.api.contracts.customer.VisitCollection
	*/
	public com.mozu.api.contracts.customer.VisitCollection getVisits(String filter, Integer pageSize, String sortBy, Integer startIndex) throws Exception
	{
		MozuClient<com.mozu.api.contracts.customer.VisitCollection> client = com.mozu.api.clients.commerce.customer.VisitClient.getVisitsClient( filter,  pageSize,  sortBy,  startIndex);
		setContext(_apiContext, client,true);
		client.executeRequest();
		return client.getResult();

	}

	
}



