/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.clients.commerce.catalog.admin.attributedefinition.attributes;

import java.util.ArrayList;
import com.mozu.api.MozuClient;

/// <summary>
/// Vocabulary values are predefined for an attribute.
/// </summary>
public class AttributeVocabularyValueClient {
	
	
	/**
	* Retrieves a list of attribute vocabulary values. To target a query, use one or several valid optional response groups.
	* <p><pre><code>
	*   MozuClient<ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>> mozuClient=GetAttributeVocabularyValuesClient( attributeFQN);
	* client.setBaseAddress(url);
	* client.executeRequest();
	* AttributeVocabularyValue attributeVocabularyValue = client.Result();
	* </code></pre></p>
	* @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
	* @return Mozu.Api.MozuClient <List<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>>
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	*/
	public static MozuClient<ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>> getAttributeVocabularyValuesClient(String attributeFQN) throws Exception
	{
		String url = com.mozu.api.urls.commerce.catalog.admin.attributedefinition.attributes.AttributeVocabularyValueUrl.getAttributeVocabularyValuesUrl(attributeFQN);
		String verb = "GET";
		Class<?> clz = new ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>(){}.getClass();
		MozuClient<ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		return mozuClient;

	}

/**
	* Retrieves an attribute vocabulary value by providing the attribute FQN and value.
	* <p><pre><code>
	*   MozuClient<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> mozuClient=GetAttributeVocabularyValueClient( attributeFQN,  value);
	* client.setBaseAddress(url);
	* client.executeRequest();
	* AttributeVocabularyValue attributeVocabularyValue = client.Result();
	* </code></pre></p>
	* @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
	* @param value The actual unique value of the attribute vocabulary to retrieve. A single attribute must have a unique value and match the attribute's data type. If a string value returns null, the system will generate a value. The actual string content displayed shoud be stored as "Content" and actual content is required for string values.
	* @return Mozu.Api.MozuClient <com.mozu.api.contracts.productadmin.AttributeVocabularyValue>
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	*/
	public static MozuClient<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> getAttributeVocabularyValueClient(String attributeFQN, String value) throws Exception
	{
		String url = com.mozu.api.urls.commerce.catalog.admin.attributedefinition.attributes.AttributeVocabularyValueUrl.getAttributeVocabularyValueUrl(attributeFQN, value);
		String verb = "GET";
		Class<?> clz = com.mozu.api.contracts.productadmin.AttributeVocabularyValue.class;
		MozuClient<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		return mozuClient;

	}

	/**
	* Adds a new attribute vocabulary value.
	* <p><pre><code>
	*   MozuClient<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> mozuClient=AddAttributeVocabularyValueClient( attributeFQN,  attributeVocabularyValue);
	* client.setBaseAddress(url);
	* client.executeRequest();
	* AttributeVocabularyValue attributeVocabularyValue = client.Result();
	* </code></pre></p>
	* @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
	* @param attributeVocabularyValue The predefined vocabulary value to add to the attribute content.
	* @return Mozu.Api.MozuClient <com.mozu.api.contracts.productadmin.AttributeVocabularyValue>
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	*/
	public static MozuClient<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> addAttributeVocabularyValueClient(String attributeFQN, com.mozu.api.contracts.productadmin.AttributeVocabularyValue attributeVocabularyValue) throws Exception
	{
		String url = com.mozu.api.urls.commerce.catalog.admin.attributedefinition.attributes.AttributeVocabularyValueUrl.addAttributeVocabularyValueUrl(attributeFQN);
		String verb = "POST";
		Class<?> clz = com.mozu.api.contracts.productadmin.AttributeVocabularyValue.class;
		MozuClient<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.setBody(attributeVocabularyValue);
		return mozuClient;

	}

	/**
	* Update existing vocabulary values for an attribute.
	* <p><pre><code>
	*   MozuClient<ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>> mozuClient=UpdateAttributeVocabularyValuesClient( attributeFQN,  vocabularyValues);
	* client.setBaseAddress(url);
	* client.executeRequest();
	* AttributeVocabularyValue attributeVocabularyValue = client.Result();
	* </code></pre></p>
	* @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
	* @param vocabularyValues The actual vocabulary values for the attribute being updated.
	* @return Mozu.Api.MozuClient <List<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>>
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	*/
	public static MozuClient<ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>> updateAttributeVocabularyValuesClient(String attributeFQN, ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> vocabularyValues) throws Exception
	{
		String url = com.mozu.api.urls.commerce.catalog.admin.attributedefinition.attributes.AttributeVocabularyValueUrl.updateAttributeVocabularyValuesUrl(attributeFQN);
		String verb = "PUT";
		Class<?> clz = new ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>(){}.getClass();
		MozuClient<ArrayList<com.mozu.api.contracts.productadmin.AttributeVocabularyValue>> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.setBody(vocabularyValues);
		return mozuClient;

	}

/**
	* Updates existing attribute vocabulary values.
	* <p><pre><code>
	*   MozuClient<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> mozuClient=UpdateAttributeVocabularyValueClient( attributeFQN,  value,  attributeVocabularyValue);
	* client.setBaseAddress(url);
	* client.executeRequest();
	* AttributeVocabularyValue attributeVocabularyValue = client.Result();
	* </code></pre></p>
	* @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
	* @param value The actual unique value of the attribute vocabulary value to update. A single attribute must have a unique value and match the attribute's data type. If a string value returns null, the system will generate a value. The actual string content displayed shoud be stored as "Content" and actual content is required for string values.
	* @param attributeVocabularyValue The predefined vocabulary value to add to the attribute content to update.
	* @return Mozu.Api.MozuClient <com.mozu.api.contracts.productadmin.AttributeVocabularyValue>
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	* @see com.mozu.api.contracts.productadmin.AttributeVocabularyValue
	*/
	public static MozuClient<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> updateAttributeVocabularyValueClient(String attributeFQN, String value, com.mozu.api.contracts.productadmin.AttributeVocabularyValue attributeVocabularyValue) throws Exception
	{
		String url = com.mozu.api.urls.commerce.catalog.admin.attributedefinition.attributes.AttributeVocabularyValueUrl.updateAttributeVocabularyValueUrl(attributeFQN, value);
		String verb = "PUT";
		Class<?> clz = com.mozu.api.contracts.productadmin.AttributeVocabularyValue.class;
		MozuClient<com.mozu.api.contracts.productadmin.AttributeVocabularyValue> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.setBody(attributeVocabularyValue);
		return mozuClient;

	}

	/**
	* Deletes an attribute's vocabulary value.
	* <p><pre><code>
	*   MozuClient mozuClient=DeleteAttributeVocabularyValueClient( attributeFQN,  value);
	* client.setBaseAddress(url);
	* client.executeRequest();
	* </code></pre></p>
	* @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
	* @param value The actual unique value of the attribute vocabulary to delete. A single attribute must have a unique value and match the attribute's data type. If a string value returns null, the system will generate a value. The actual string content displayed shoud be stored as "Content" and actual content is required for string values.
	* @return Mozu.Api.MozuClient 
	*/
	public static MozuClient deleteAttributeVocabularyValueClient(String attributeFQN, String value) throws Exception
	{
		String url = com.mozu.api.urls.commerce.catalog.admin.attributedefinition.attributes.AttributeVocabularyValueUrl.deleteAttributeVocabularyValueUrl(attributeFQN, value);
		String verb = "DELETE";
				MozuClient mozuClient = new MozuClient();
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		return mozuClient;

	}


}



