
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.urls.commerce.catalog.admin.products;

import com.mozu.api.utils.UrlFormatter;


public class ProductExtraUrl
{

	/**
        * Get Resource Url for GetExtras
        * @param productCode Merchant-created code that uniquely identifies the product such as a SKU or item number. Once created, the product code is read-only.
        * @return    String Resource Url
    */
	public static String getExtrasUrl(String productCode)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/products/{productCode}/Extras");
		formatter.formatUrl("productCode", productCode);
		return formatter.getResourceUrl();
	}

	/**
        * Get Resource Url for GetExtra
        * @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
        * @param productCode Merchant-created code that uniquely identifies the product such as a SKU or item number. Once created, the product code is read-only.
        * @return    String Resource Url
    */
	public static String getExtraUrl(String attributeFQN, String productCode)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/products/{productCode}/Extras/{attributeFQN}");
		formatter.formatUrl("attributeFQN", attributeFQN);
		formatter.formatUrl("productCode", productCode);
		return formatter.getResourceUrl();
	}

		/**
        * Get Resource Url for AddExtra
        * @param productCode Merchant-created code that uniquely identifies the product such as a SKU or item number. Once created, the product code is read-only.
        * @return    String Resource Url
    */
	public static String addExtraUrl(String productCode)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/products/{productCode}/Extras");
		formatter.formatUrl("productCode", productCode);
		return formatter.getResourceUrl();
	}

		/**
        * Get Resource Url for UpdateExtra
        * @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
        * @param productCode Merchant-created code that uniquely identifies the product such as a SKU or item number. Once created, the product code is read-only.
        * @return    String Resource Url
    */
	public static String updateExtraUrl(String attributeFQN, String productCode)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/products/{productCode}/Extras/{attributeFQN}");
		formatter.formatUrl("attributeFQN", attributeFQN);
		formatter.formatUrl("productCode", productCode);
		return formatter.getResourceUrl();
	}

		/**
        * Get Resource Url for DeleteExtra
        * @param attributeFQN The fully qualified name of the attribute, which is a user defined attribute identifier.
        * @param productCode Merchant-created code that uniquely identifies the product such as a SKU or item number. Once created, the product code is read-only.
        * @return    String Resource Url
    */
	public static String deleteExtraUrl(String attributeFQN, String productCode)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/products/{productCode}/Extras/{attributeFQN}");
		formatter.formatUrl("attributeFQN", attributeFQN);
		formatter.formatUrl("productCode", productCode);
		return formatter.getResourceUrl();
	}

	
}

