/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.urls.commerce.catalog.admin.products;

import com.mozu.api.MozuUrl;
import com.mozu.api.utils.UrlFormatter;


public class ProductVariationUrl
{

	/**
	 * Get Resource Url for GetProductVariation
	 * @param productCode 
	 * @param variationKey 
	 * @return   String Resource Url
	 */
	public static MozuUrl getProductVariationUrl(String productCode, String variationKey)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}");
		formatter.formatUrl("productCode", productCode);
		formatter.formatUrl("variationKey", variationKey);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for GetProductVariations
	 * @param filter 
	 * @param pageSize 
	 * @param productCode 
	 * @param sortBy 
	 * @param startIndex 
	 * @return   String Resource Url
	 */
	public static MozuUrl getProductVariationsUrl(String filter, Integer pageSize, String productCode, String sortBy, Integer startIndex)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/products/{productCode}/variations?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}");
		formatter.formatUrl("filter", filter);
		formatter.formatUrl("pageSize", pageSize);
		formatter.formatUrl("productCode", productCode);
		formatter.formatUrl("sortBy", sortBy);
		formatter.formatUrl("startIndex", startIndex);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for UpdateProductVariations
	 * @param productCode 
	 * @return   String Resource Url
	 */
	public static MozuUrl updateProductVariationsUrl(String productCode)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/products/{productCode}/variations");
		formatter.formatUrl("productCode", productCode);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for UpdateProductVariation
	 * @param productCode 
	 * @param variationKey 
	 * @return   String Resource Url
	 */
	public static MozuUrl updateProductVariationUrl(String productCode, String variationKey)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}");
		formatter.formatUrl("productCode", productCode);
		formatter.formatUrl("variationKey", variationKey);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for DeleteProductVariation
	 * @param productCode 
	 * @param variationKey 
	 * @return   String Resource Url
	 */
	public static MozuUrl deleteProductVariationUrl(String productCode, String variationKey)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}");
		formatter.formatUrl("productCode", productCode);
		formatter.formatUrl("variationKey", variationKey);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

}

