/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.contracts.paymentservice;

import java.util.List;
import java.io.Serializable;
import java.util.Date;
import com.mozu.api.contracts.paymentservice.GatewayCredentialFieldValue;

public class GatewayAccount implements Serializable
{
	// Default Serial Version UID
	private static final long serialVersionUID = 1L;

	protected String countryCode;

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	protected String gatewayDefinitionId;

	public String getGatewayDefinitionId() {
		return this.gatewayDefinitionId;
	}

	public void setGatewayDefinitionId(String gatewayDefinitionId) {
		this.gatewayDefinitionId = gatewayDefinitionId;
	}

	protected String id;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	protected Boolean isActive;

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	protected List<GatewayCredentialFieldValue> credentialFields;
	public List<GatewayCredentialFieldValue> getCredentialFields() {
		return this.credentialFields;
	}
	public void setCredentialFields(List<GatewayCredentialFieldValue> credentialFields) {
		this.credentialFields = credentialFields;
	}

}
