/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.resources.commerce.settings;

import com.mozu.api.ApiContext;
import com.mozu.api.resources.BaseResource;
import java.util.ArrayList;
import com.mozu.api.MozuClient;

/// <summary>
/// Use the applications subresource to update site settings for installed applications.
/// </summary>
public class ApplicationResource extends BaseResource {
	///
	/// <see cref="Mozu.Api.ApiContext"/>
	///
	private ApiContext _apiContext;
	
	public ApplicationResource(ApiContext apiContext) 
	{
		_apiContext = apiContext;
	}
	
			/**
	* Initializes an application with the necessary configured settings.
	* <p><pre><code>
	*    Application application = new Application();
	*   Application application = application.ThirdPartyUpdateApplication( application);
	* </code></pre></p>
	* @param application Properties of the application to update.
	* @return com.mozu.api.contracts.sitesettings.application.Application
	* @see com.mozu.api.contracts.sitesettings.application.Application
	* @see com.mozu.api.contracts.sitesettings.application.Application
	*/
	public com.mozu.api.contracts.sitesettings.application.Application thirdPartyUpdateApplication(com.mozu.api.contracts.sitesettings.application.Application application) throws Exception
	{
		MozuClient<com.mozu.api.contracts.sitesettings.application.Application> client = com.mozu.api.clients.commerce.settings.ApplicationClient.thirdPartyUpdateApplicationClient( application);
		setContext(_apiContext, client,true);
		client.executeRequest();
		return client.getResult();

	}

	
}



