/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.resources.commerce.settings;

import com.mozu.api.ApiContext;
import java.util.List;
import java.util.ArrayList;
import com.mozu.api.MozuClient;
import com.mozu.api.MozuUrl;
import com.mozu.api.Headers;
import com.mozu.api.security.AuthTicket;

/** <summary>
 * Define global site settings such as the site name, shipping and email addresses, and logo images. Block undesirable IP addresses using this resource.
 * </summary>
 */
public class GeneralSettingsResource {
	///
	/// <see cref="Mozu.Api.ApiContext"/>
	///
	private ApiContext _apiContext;
	public GeneralSettingsResource(ApiContext apiContext) 
	{
		_apiContext = apiContext;
	}
	
	/**
	 * Retrieve a site's general global settings.
	 * <p><pre><code>
	 *	GeneralSettings generalsettings = new GeneralSettings();
	 *	GeneralSettings generalSettings = generalsettings.GetGeneralSettings(authTicket);
	 * </code></pre></p>
	 * @param authTicket User Auth Ticket
	 * @return com.mozu.api.contracts.sitesettings.general.GeneralSettings
	 * @see com.mozu.api.contracts.sitesettings.general.GeneralSettings
	 */
	public com.mozu.api.contracts.sitesettings.general.GeneralSettings getGeneralSettings(AuthTicket authTicket) throws Exception
	{
		MozuClient<com.mozu.api.contracts.sitesettings.general.GeneralSettings> client = com.mozu.api.clients.commerce.settings.GeneralSettingsClient.getGeneralSettingsClient(authTicket);
		client.setContext(_apiContext);
		client.executeRequest();
		return client.getResult();

	}

	/**
	 * Updates a site's general global settings.
	 * <p><pre><code>
	 *	GeneralSettings generalsettings = new GeneralSettings();
	 *	GeneralSettings generalSettings = generalsettings.UpdateGeneralSettings( generalSettings, authTicket);
	 * </code></pre></p>
	 * @param authTicket User Auth Ticket
	 * @param generalSettings The properties of the site's general settings to update.
	 * @return com.mozu.api.contracts.sitesettings.general.GeneralSettings
	 * @see com.mozu.api.contracts.sitesettings.general.GeneralSettings
	 * @see com.mozu.api.contracts.sitesettings.general.GeneralSettings
	 */
	public com.mozu.api.contracts.sitesettings.general.GeneralSettings updateGeneralSettings(com.mozu.api.contracts.sitesettings.general.GeneralSettings generalSettings, AuthTicket authTicket) throws Exception
	{
		MozuClient<com.mozu.api.contracts.sitesettings.general.GeneralSettings> client = com.mozu.api.clients.commerce.settings.GeneralSettingsClient.updateGeneralSettingsClient( generalSettings, authTicket);
		client.setContext(_apiContext);
		client.executeRequest();
		return client.getResult();

	}

}



