/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.contracts.sitesettings.order;

import java.io.Serializable;
import java.util.Date;
import com.mozu.api.contracts.core.AuditInfo;

public class CustomerCheckoutSettings implements Serializable
{
	// Default Serial Version UID
	private static final long serialVersionUID = 1L;

	protected String customerCheckoutType;

	public String getCustomerCheckoutType() {
		return this.customerCheckoutType;
	}

	public void setCustomerCheckoutType(String customerCheckoutType) {
		this.customerCheckoutType = customerCheckoutType;
	}

	protected AuditInfo auditInfo;

	public AuditInfo getAuditInfo() {
		return this.auditInfo;
	}

	public void setAuditInfo(AuditInfo auditInfo) {
		this.auditInfo = auditInfo;
	}

}
