/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.contracts.sitesettings.order;

import java.util.List;
import java.io.Serializable;
import java.util.Date;
import com.mozu.api.contracts.sitesettings.order.ThirdPartyCredentialField;

public class ExternalPaymentWorkflowDefinition implements Serializable
{
	// Default Serial Version UID
	private static final long serialVersionUID = 1L;

	protected Boolean isEnabled;

	public Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	protected String name;

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	protected List<ThirdPartyCredentialField> credentials;
	public List<ThirdPartyCredentialField> getCredentials() {
		return this.credentials;
	}
	public void setCredentials(List<ThirdPartyCredentialField> credentials) {
		this.credentials = credentials;
	}

}
