
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.urls.commerce.settings;

import com.mozu.api.utils.UrlFormatter;


public class GeneralSettingsUrl
{

	/**
        * Get Resource Url for GetGeneralSettings
        * @return    String Resource Url
    */
	public static String getGeneralSettingsUrl()
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/settings/general/");
		return formatter.getResourceUrl();
	}

			/**
        * Get Resource Url for UpdateGeneralSettings
        * @return    String Resource Url
    */
	public static String updateGeneralSettingsUrl()
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/settings/general/");
		return formatter.getResourceUrl();
	}

		
}

