
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.sitesettings.general;

import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mozu.api.contracts.core.AuditInfo;


/**
*	Use the IP Blocks subresource to manage site blocking settings for an individual IP address or for a range of IP addresses that are potentially malicious.
*/
public class IPBlock implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	/**
	*If true, the IP block prevents access to the site's admin area. Default: False.
	*/
	@JsonProperty("AdminBlock")
	protected Boolean adminBlock;

	public Boolean getAdminBlock() {
		return this.adminBlock;
	}

	public void setAdminBlock(Boolean adminBlock) {
		this.adminBlock = adminBlock;
	}

	/**
	*Identifier of the IP block.
	*/
	@JsonProperty("Id")
	protected Integer id;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/**
	*In a range of IP addresses to block, this string is the last IP address in the order.
	*/
	@JsonProperty("RangeEnd")
	protected String rangeEnd;

	public String getRangeEnd() {
		return this.rangeEnd;
	}

	public void setRangeEnd(String rangeEnd) {
		this.rangeEnd = rangeEnd;
	}

	/**
	*In a range of IP addresses to block, this string is the first IP address to block. If no RangeEnd is specified, the system will block the only IP address provided.
	*/
	@JsonProperty("RangeStart")
	protected String rangeStart;

	public String getRangeStart() {
		return this.rangeStart;
	}

	public void setRangeStart(String rangeStart) {
		this.rangeStart = rangeStart;
	}

	/**
	*If true, the IP block prevents access to the site's storefront. Default: False.
	*/
	@JsonProperty("StoreFrontBlock")
	protected Boolean storeFrontBlock;

	public Boolean getStoreFrontBlock() {
		return this.storeFrontBlock;
	}

	public void setStoreFrontBlock(Boolean storeFrontBlock) {
		this.storeFrontBlock = storeFrontBlock;
	}

	/**
	*Identifier and datetime stamp information recorded when creating or updating a resource entity. This value is system-supplied and read-only.
	*/
	@JsonProperty("AuditInfo")
	protected AuditInfo auditInfo;

	public AuditInfo getAuditInfo() {
		return this.auditInfo;
	}

	public void setAuditInfo(AuditInfo auditInfo) {
		this.auditInfo = auditInfo;
	}

}
