/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.clients.content.documentlists;

import java.util.List;
import java.util.ArrayList;
import com.mozu.api.MozuClient;
import com.mozu.api.MozuUrl;
import com.mozu.api.Headers;
import com.mozu.api.security.AuthTicket;

/** <summary>
 * 
 * </summary>
 */
public class FolderTreeClient {
	
	/**
	 * 
	 * <p><pre><code>
	 * MozuClient<com.mozu.api.contracts.content.FolderTree> mozuClient=GetFolderTreeClient( documentListName);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * FolderTree folderTree = client.Result();
	 * </code></pre></p>
	 * @param documentListName 
	 * @param authTicket User Auth Ticket
	 * @return Mozu.Api.MozuClient <com.mozu.api.contracts.content.FolderTree>
	 * @see com.mozu.api.contracts.content.FolderTree
	 */
	public static MozuClient<com.mozu.api.contracts.content.FolderTree> getFolderTreeClient(String documentListName) throws Exception
	{
		return getFolderTreeClient( documentListName,  null,  null,  null, null);
	}

	/**
	 * 
	 * <p><pre><code>
	 * MozuClient<com.mozu.api.contracts.content.FolderTree> mozuClient=GetFolderTreeClient( documentListName,  levels,  rootFolderId,  rootFolderPath, authTicket);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * FolderTree folderTree = client.Result();
	 * </code></pre></p>
	 * @param documentListName 
	 * @param levels 
	 * @param rootFolderId 
	 * @param rootFolderPath 
	 * @param authTicket User Auth Ticket
	 * @return Mozu.Api.MozuClient <com.mozu.api.contracts.content.FolderTree>
	 * @see com.mozu.api.contracts.content.FolderTree
	 */
	public static MozuClient<com.mozu.api.contracts.content.FolderTree> getFolderTreeClient(String documentListName, Integer levels, String rootFolderId, String rootFolderPath, AuthTicket authTicket) throws Exception
	{
		MozuUrl url = com.mozu.api.urls.content.documentlists.FolderTreeUrl.getFolderTreeUrl(documentListName, levels, rootFolderId, rootFolderPath);
		String verb = "GET";
		Class<?> clz = com.mozu.api.contracts.content.FolderTree.class;
		MozuClient<com.mozu.api.contracts.content.FolderTree> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		if (authTicket != null)
			mozuClient.setUserAuth(authTicket);
		return mozuClient;

	}

}



