/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.clients.commerce.settings;

import java.util.List;
import java.util.ArrayList;
import com.mozu.api.MozuClient;
import com.mozu.api.MozuUrl;
import com.mozu.api.Headers;
import com.mozu.api.security.AuthTicket;

/** <summary>
 * 
 * </summary>
 */
public class LocationUsageClient {
	
	/**
	 * 
	 * <p><pre><code>
	 * MozuClient<com.mozu.api.contracts.location.LocationUsageCollection> mozuClient=GetLocationUsagesClient(authTicket);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * LocationUsageCollection locationUsageCollection = client.Result();
	 * </code></pre></p>
	 * @param authTicket User Auth Ticket
	 * @return Mozu.Api.MozuClient <com.mozu.api.contracts.location.LocationUsageCollection>
	 * @see com.mozu.api.contracts.location.LocationUsageCollection
	 */
	public static MozuClient<com.mozu.api.contracts.location.LocationUsageCollection> getLocationUsagesClient(AuthTicket authTicket) throws Exception
	{
		MozuUrl url = com.mozu.api.urls.commerce.settings.LocationUsageUrl.getLocationUsagesUrl();
		String verb = "GET";
		Class<?> clz = com.mozu.api.contracts.location.LocationUsageCollection.class;
		MozuClient<com.mozu.api.contracts.location.LocationUsageCollection> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		if (authTicket != null)
			mozuClient.setUserAuth(authTicket);
		return mozuClient;

	}

	/**
	 * 
	 * <p><pre><code>
	 * MozuClient<com.mozu.api.contracts.location.LocationUsage> mozuClient=GetLocationUsageClient( code, authTicket);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * LocationUsage locationUsage = client.Result();
	 * </code></pre></p>
	 * @param code 
	 * @param authTicket User Auth Ticket
	 * @return Mozu.Api.MozuClient <com.mozu.api.contracts.location.LocationUsage>
	 * @see com.mozu.api.contracts.location.LocationUsage
	 */
	public static MozuClient<com.mozu.api.contracts.location.LocationUsage> getLocationUsageClient(String code, AuthTicket authTicket) throws Exception
	{
		MozuUrl url = com.mozu.api.urls.commerce.settings.LocationUsageUrl.getLocationUsageUrl(code);
		String verb = "GET";
		Class<?> clz = com.mozu.api.contracts.location.LocationUsage.class;
		MozuClient<com.mozu.api.contracts.location.LocationUsage> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		if (authTicket != null)
			mozuClient.setUserAuth(authTicket);
		return mozuClient;

	}

	/**
	 * 
	 * <p><pre><code>
	 * MozuClient<com.mozu.api.contracts.location.LocationUsage> mozuClient=UpdateLocationUsageClient( usage,  code, authTicket);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * LocationUsage locationUsage = client.Result();
	 * </code></pre></p>
	 * @param code 
	 * @param authTicket User Auth Ticket
	 * @param usage 
	 * @return Mozu.Api.MozuClient <com.mozu.api.contracts.location.LocationUsage>
	 * @see com.mozu.api.contracts.location.LocationUsage
	 * @see com.mozu.api.contracts.location.LocationUsage
	 */
	public static MozuClient<com.mozu.api.contracts.location.LocationUsage> updateLocationUsageClient(com.mozu.api.contracts.location.LocationUsage usage, String code, AuthTicket authTicket) throws Exception
	{
		MozuUrl url = com.mozu.api.urls.commerce.settings.LocationUsageUrl.updateLocationUsageUrl(code);
		String verb = "PUT";
		Class<?> clz = com.mozu.api.contracts.location.LocationUsage.class;
		MozuClient<com.mozu.api.contracts.location.LocationUsage> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.setBody(usage);
		if (authTicket != null)
			mozuClient.setUserAuth(authTicket);
		return mozuClient;

	}

}



