
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.urls.platform.adminuser;

import com.mozu.api.utils.UrlFormatter;


public class AdminUserUrl
{

	/**
        * Get Resource Url for GetUser
        * @param userId Unique identifier of the administrator account to retrieve.
        * @return    String Resource Url
    */
	public static String getUserUrl(String userId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/platform/adminuser/accounts/{userId}");
		formatter.formatUrl("userId", userId);
		return formatter.getResourceUrl();
	}

	/**
        * Get Resource Url for GetTenantScopesForUser
        * @param userId Unique identifier of the user whose tenant scopes you want to retrieve.
        * @return    String Resource Url
    */
	public static String getTenantScopesForUserUrl(String userId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/platform/adminuser/accounts/{userId}/tenants");
		formatter.formatUrl("userId", userId);
		return formatter.getResourceUrl();
	}

				
}

