/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.clients.platform;

import java.util.List;
import java.util.ArrayList;
import com.mozu.api.MozuClient;
import com.mozu.api.MozuUrl;
import com.mozu.api.Headers;
import com.mozu.api.security.AuthTicket;

/** <summary>
 * 
 * </summary>
 */
public class TenantDataClient {
	
	/**
	 * 
	 * <p><pre><code>
	 * MozuClient<String> mozuClient=GetDBValueClient( dbEntryQuery);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * string string = client.Result();
	 * </code></pre></p>
	 * @param dbEntryQuery 
	 * @return Mozu.Api.MozuClient <string>
	 * @see string
	 */
	public static MozuClient<String> getDBValueClient(String dbEntryQuery) throws Exception
	{
		MozuUrl url = com.mozu.api.urls.platform.TenantDataUrl.getDBValueUrl(dbEntryQuery);
		String verb = "GET";
		Class<?> clz = String.class;
		MozuClient<String> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		return mozuClient;

	}

	/**
	 * 
	 * <p><pre><code>
	 * MozuClient mozuClient=CreateDBValueClient( value,  dbEntryQuery);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * </code></pre></p>
	 * @param dbEntryQuery 
	 * @param value 
	 * @return Mozu.Api.MozuClient 
	 * @see string
	 */
	public static MozuClient createDBValueClient(String value, String dbEntryQuery) throws Exception
	{
		MozuUrl url = com.mozu.api.urls.platform.TenantDataUrl.createDBValueUrl(dbEntryQuery);
		String verb = "POST";
				MozuClient mozuClient = new MozuClient();
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.setBody(value);
		return mozuClient;

	}

	/**
	 * 
	 * <p><pre><code>
	 * MozuClient mozuClient=UpdateDBValueClient( value,  dbEntryQuery);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * </code></pre></p>
	 * @param dbEntryQuery 
	 * @param value 
	 * @return Mozu.Api.MozuClient 
	 * @see string
	 */
	public static MozuClient updateDBValueClient(String value, String dbEntryQuery) throws Exception
	{
		MozuUrl url = com.mozu.api.urls.platform.TenantDataUrl.updateDBValueUrl(dbEntryQuery);
		String verb = "PUT";
				MozuClient mozuClient = new MozuClient();
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.setBody(value);
		return mozuClient;

	}

	/**
	 * 
	 * <p><pre><code>
	 * MozuClient mozuClient=DeleteDBValueClient( dbEntryQuery);
	 * client.setBaseAddress(url);
	 * client.executeRequest();
	 * </code></pre></p>
	 * @param dbEntryQuery 
	 * @return Mozu.Api.MozuClient 
	 */
	public static MozuClient deleteDBValueClient(String dbEntryQuery) throws Exception
	{
		MozuUrl url = com.mozu.api.urls.platform.TenantDataUrl.deleteDBValueUrl(dbEntryQuery);
		String verb = "DELETE";
				MozuClient mozuClient = new MozuClient();
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		return mozuClient;

	}

}



