
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.sitesettings.application;

import java.util.ArrayList;
import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mozu.api.contracts.core.AuditInfo;
import com.mozu.api.contracts.core.thirdparty.Capability;
import com.mozu.api.contracts.tenant.Entitlement;


/**
*	Properties of an application installed in a tenant.
*/
public class Application implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	/**
	*The unique identifier of the application in Dev Center.
	*/
	@JsonProperty("AppId")
	protected String appId;

	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
	*If true, the application is enabled for the tenant. System-supplied and read only.
	*/
	@JsonProperty("Enabled")
	protected Boolean enabled;

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	/**
	*If true, the third party application settings have been configured and the application is initialized.
	*/
	@JsonProperty("Initialized")
	protected Boolean initialized;

	public Boolean getInitialized() {
		return this.initialized;
	}

	public void setInitialized(Boolean initialized) {
		this.initialized = initialized;
	}

	/**
	*URL of the application's setting configuration user interface. System-supplied and read only.
	*/
	@JsonProperty("UIConfigurationUrl")
	protected String uIConfigurationUrl;

	public String getUIConfigurationUrl() {
		return this.uIConfigurationUrl;
	}

	public void setUIConfigurationUrl(String uIConfigurationUrl) {
		this.uIConfigurationUrl = uIConfigurationUrl;
	}

	@JsonProperty("AuditInfo")
	protected AuditInfo auditInfo;

	public AuditInfo getAuditInfo() {
		return this.auditInfo;
	}

	public void setAuditInfo(AuditInfo auditInfo) {
		this.auditInfo = auditInfo;
	}

	/**
	*List of capabilities installed in a tenant.
	*/
	@JsonProperty("Capabilities")
	protected ArrayList<Capability> capabilities;
	public ArrayList<Capability> getCapabilities() {
		return this.capabilities;
	}
	public void setCapabilities(ArrayList<Capability> capabilities) {
		this.capabilities = capabilities;
	}

	/**
	*Properties of the capability application entitlement record, including the merchant it is licensed to and the duration of the license.
	*/
	@JsonProperty("Entitlement")
	protected Entitlement entitlement;

	public Entitlement getEntitlement() {
		return this.entitlement;
	}

	public void setEntitlement(Entitlement entitlement) {
		this.entitlement = entitlement;
	}

}
