
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.urls.commerce.catalog.admin;

import com.mozu.api.utils.UrlFormatter;


public class DiscountUrl
{

	/**
        * Get Resource Url for GetDiscounts
        * @param filter A set of expressions that consist of a field, operator, and value and represent search parameter syntax when filtering results of a query. Valid operators include equals (eq), does not equal (ne), greater than (gt), less than (lt), greater than or equal to (ge), less than or equal to (le), starts with (sw), or contains (cont). For example - "filter=IsDisplayed+eq+true"
        * @param pageSize Specifies the number of results to display on each page when creating paged results from a query. The maximum value is 200.
        * @param sortBy 
        * @param startIndex 
        * @return    String Resource Url
    */
	public static String getDiscountsUrl(String filter, Integer pageSize, String sortBy, Integer startIndex)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/discounts/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&");
		formatter.formatUrl("filter", filter);
		formatter.formatUrl("pageSize", pageSize);
		formatter.formatUrl("sortBy", sortBy);
		formatter.formatUrl("startIndex", startIndex);
		return formatter.getResourceUrl();
	}

	/**
        * Get Resource Url for GetDiscount
        * @param discountId Unique identifier of the discount. System-supplied and read-only.
        * @return    String Resource Url
    */
	public static String getDiscountUrl(Integer discountId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/discounts/{discountId}");
		formatter.formatUrl("discountId", discountId);
		return formatter.getResourceUrl();
	}

	/**
        * Get Resource Url for GetDiscountContent
        * @param discountId Unique identifier of the discount. System-supplied and read-only.
        * @return    String Resource Url
    */
	public static String getDiscountContentUrl(Integer discountId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/discounts/{discountId}/content");
		formatter.formatUrl("discountId", discountId);
		return formatter.getResourceUrl();
	}

	/**
        * Get Resource Url for GenerateRandomCoupon
        * @return    String Resource Url
    */
	public static String generateRandomCouponUrl()
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/discounts/generate-random-coupon");
		return formatter.getResourceUrl();
	}

		/**
        * Get Resource Url for CreateDiscount
        * @return    String Resource Url
    */
	public static String createDiscountUrl()
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/discounts/");
		return formatter.getResourceUrl();
	}

	/**
        * Get Resource Url for RedeemDiscount
        * @return    String Resource Url
    */
	public static String redeemDiscountUrl()
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/discounts/Redeem");
		return formatter.getResourceUrl();
	}

		/**
        * Get Resource Url for UpdateDiscount
        * @param discountId Unique identifier of the discount. System-supplied and read-only.
        * @return    String Resource Url
    */
	public static String updateDiscountUrl(Integer discountId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/discounts/{discountId}");
		formatter.formatUrl("discountId", discountId);
		return formatter.getResourceUrl();
	}

	/**
        * Get Resource Url for UpdateDiscountContent
        * @param discountId Unique identifier of the discount. System-supplied and read-only.
        * @return    String Resource Url
    */
	public static String updateDiscountContentUrl(Integer discountId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/discounts/{discountId}/content");
		formatter.formatUrl("discountId", discountId);
		return formatter.getResourceUrl();
	}

		/**
        * Get Resource Url for DeleteDiscount
        * @param discountId Unique identifier of the discount. System-supplied and read-only.
        * @return    String Resource Url
    */
	public static String deleteDiscountUrl(Integer discountId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/discounts/{discountId}");
		formatter.formatUrl("discountId", discountId);
		return formatter.getResourceUrl();
	}

	/**
        * Get Resource Url for UnRedeemDiscount
        * @param discountId Unique identifier of the previously redeemed discount. System-supplied and read only.
        * @param orderNumber The number of the order associated with the redeemed product discount.
        * @return    String Resource Url
    */
	public static String unRedeemDiscountUrl(Integer discountId, Integer orderNumber)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/discounts/{discountId}/Unredeem/{orderNumber}");
		formatter.formatUrl("discountId", discountId);
		formatter.formatUrl("orderNumber", orderNumber);
		return formatter.getResourceUrl();
	}

	
}

