
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.tenant;

import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;


/**
*	***Always private and should not be published.***
*/
public class Entitlement implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	@JsonProperty("AppConfigUrl")
	protected String appConfigUrl;

	public String getAppConfigUrl() {
		return this.appConfigUrl;
	}

	public void setAppConfigUrl(String appConfigUrl) {
		this.appConfigUrl = appConfigUrl;
	}

	@JsonProperty("AppId")
	protected String appId;

	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	@JsonProperty("ApplicationAssetPath")
	protected String applicationAssetPath;

	public String getApplicationAssetPath() {
		return this.applicationAssetPath;
	}

	public void setApplicationAssetPath(String applicationAssetPath) {
		this.applicationAssetPath = applicationAssetPath;
	}

	@JsonProperty("ApplicationName")
	protected String applicationName;

	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	@JsonProperty("ApplicationType")
	protected String applicationType;

	public String getApplicationType() {
		return this.applicationType;
	}

	public void setApplicationType(String applicationType) {
		this.applicationType = applicationType;
	}

	@JsonProperty("ApplicationVersion")
	protected String applicationVersion;

	public String getApplicationVersion() {
		return this.applicationVersion;
	}

	public void setApplicationVersion(String applicationVersion) {
		this.applicationVersion = applicationVersion;
	}

	/**
	****Always private and should not be published.***
	*/
	@JsonProperty("ApplicationVersionId")
	protected Integer applicationVersionId;

	public Integer getApplicationVersionId() {
		return this.applicationVersionId;
	}

	public void setApplicationVersionId(Integer applicationVersionId) {
		this.applicationVersionId = applicationVersionId;
	}

	/**
	*Date and time when the entity was created, represented in UTC Date/Time.
	*/
	@JsonProperty("CreateDate")
	protected Date createDate;

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@JsonProperty("DeveloperAccountName")
	protected String developerAccountName;

	public String getDeveloperAccountName() {
		return this.developerAccountName;
	}

	public void setDeveloperAccountName(String developerAccountName) {
		this.developerAccountName = developerAccountName;
	}

	@JsonProperty("EffectiveEndDate")
	protected Date effectiveEndDate;

	public Date getEffectiveEndDate() {
		return this.effectiveEndDate;
	}

	public void setEffectiveEndDate(Date effectiveEndDate) {
		this.effectiveEndDate = effectiveEndDate;
	}

	@JsonProperty("EffectiveStartDate")
	protected Date effectiveStartDate;

	public Date getEffectiveStartDate() {
		return this.effectiveStartDate;
	}

	public void setEffectiveStartDate(Date effectiveStartDate) {
		this.effectiveStartDate = effectiveStartDate;
	}

	@JsonProperty("HeroImage")
	protected String heroImage;

	public String getHeroImage() {
		return this.heroImage;
	}

	public void setHeroImage(String heroImage) {
		this.heroImage = heroImage;
	}

	/**
	*Identifier of the entity.
	*/
	@JsonProperty("Id")
	protected Integer id;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonProperty("LicenseType")
	protected String licenseType;

	public String getLicenseType() {
		return this.licenseType;
	}

	public void setLicenseType(String licenseType) {
		this.licenseType = licenseType;
	}

	/**
	*When the document was published. System-supplied and read-only.
	*/
	@JsonProperty("PublishedDate")
	protected Date publishedDate;

	public Date getPublishedDate() {
		return this.publishedDate;
	}

	public void setPublishedDate(Date publishedDate) {
		this.publishedDate = publishedDate;
	}

	@JsonProperty("SiteId")
	protected Integer siteId;

	public Integer getSiteId() {
		return this.siteId;
	}

	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	@JsonProperty("Status")
	protected String status;

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
	*Unique identifier of the Mozu tenant.
	*/
	@JsonProperty("TenantId")
	protected Integer tenantId;

	public Integer getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(Integer tenantId) {
		this.tenantId = tenantId;
	}

	/**
	*Date and time when the entity was last updated, represented in UTC Date/Time.
	*/
	@JsonProperty("UpdateDate")
	protected Date updateDate;

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
