
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.tenant;

import java.util.ArrayList;
import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mozu.api.contracts.tenant.Site;


/**
*	The properties that describe a site group including the create and update dates, default currency and locale codes, name, the tenant ID who owns the site group, and the site group name.
*/
public class SiteGroup implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	/**
	*Date and time when the entity was created, represented in UTC Date/Time.
	*/
	@JsonProperty("CreateDate")
	protected Date createDate;

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	*The currency code associated with the default currency for this site group.
	*/
	@JsonProperty("DefaultCurrencyCode")
	protected String defaultCurrencyCode;

	public String getDefaultCurrencyCode() {
		return this.defaultCurrencyCode;
	}

	public void setDefaultCurrencyCode(String defaultCurrencyCode) {
		this.defaultCurrencyCode = defaultCurrencyCode;
	}

	/**
	*Language used for the entity. Currently, only "en-US" is supported.
	*/
	@JsonProperty("DefaultLocaleCode")
	protected String defaultLocaleCode;

	public String getDefaultLocaleCode() {
		return this.defaultLocaleCode;
	}

	public void setDefaultLocaleCode(String defaultLocaleCode) {
		this.defaultLocaleCode = defaultLocaleCode;
	}

	@JsonProperty("DeleteDate")
	protected Date deleteDate;

	public Date getDeleteDate() {
		return this.deleteDate;
	}

	public void setDeleteDate(Date deleteDate) {
		this.deleteDate = deleteDate;
	}

	/**
	*Identifier of the site group.
	*/
	@JsonProperty("Id")
	protected Integer id;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonProperty("IsDeleted")
	protected Boolean isDeleted;

	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	*The name of the site group, if applicable.
	*/
	@JsonProperty("Name")
	protected String name;

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
	*Unique identifier of the Mozu tenant.
	*/
	@JsonProperty("TenantId")
	protected Integer tenantId;

	public Integer getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(Integer tenantId) {
		this.tenantId = tenantId;
	}

	/**
	*Date and time when the entity was last updated, represented in UTC Date/Time.
	*/
	@JsonProperty("UpdateDate")
	protected Date updateDate;

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	*Collection of sites that belong to this site group and their properties.
	*/
	@JsonProperty("Sites")
	protected ArrayList<Site> sites;
	public ArrayList<Site> getSites() {
		return this.sites;
	}
	public void setSites(ArrayList<Site> sites) {
		this.sites = sites;
	}

}
