/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.contracts.tenant;

import java.util.List;
import java.io.Serializable;
import java.util.Date;
import com.mozu.api.contracts.tenant.MasterCatalog;
import com.mozu.api.contracts.tenant.Site;

public class Tenant implements Serializable
{
	// Default Serial Version UID
	private static final long serialVersionUID = 1L;

	protected String domain;

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	protected Integer id;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	protected Boolean isDevTenant;

	public Boolean getIsDevTenant() {
		return this.isDevTenant;
	}

	public void setIsDevTenant(Boolean isDevTenant) {
		this.isDevTenant = isDevTenant;
	}

	protected String name;

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	protected List<MasterCatalog> masterCatalogs;
	public List<MasterCatalog> getMasterCatalogs() {
		return this.masterCatalogs;
	}
	public void setMasterCatalogs(List<MasterCatalog> masterCatalogs) {
		this.masterCatalogs = masterCatalogs;
	}

	protected List<Site> sites;
	public List<Site> getSites() {
		return this.sites;
	}
	public void setSites(List<Site> sites) {
		this.sites = sites;
	}

}
