/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.clients.commerce.settings.checkout;

import java.util.ArrayList;
import com.mozu.api.MozuClient;

/// <summary>
/// Use the order processing settings resource to define how orders and payments are processed for the site.
/// </summary>
public class OrderProcessingSettingsClient {
	
	
	/**
	* Retrieves a list of the order processing settings defined for the site.
	* <p><pre><code>
	*   MozuClient<com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings> mozuClient=GetOrderProcessingSettingsClient();
	* client.setBaseAddress(url);
	* client.executeRequest();
	* OrderProcessingSettings orderProcessingSettings = client.Result();
	* </code></pre></p>
	* @return Mozu.Api.MozuClient <com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings>
	* @see com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings
	*/
	public static MozuClient<com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings> getOrderProcessingSettingsClient() throws Exception
	{
		String url = com.mozu.api.urls.commerce.settings.checkout.OrderProcessingSettingsUrl.getOrderProcessingSettingsUrl();
		String verb = "GET";
		Class<?> clz = com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings.class;
		MozuClient<com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		return mozuClient;

	}

		/**
	* Updates the order processing settings defined for the site.
	* <p><pre><code>
	*   MozuClient<com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings> mozuClient=UpdateOrderProcessingSettingsClient( orderProcessingSettings);
	* client.setBaseAddress(url);
	* client.executeRequest();
	* OrderProcessingSettings orderProcessingSettings = client.Result();
	* </code></pre></p>
	* @param orderProcessingSettings List of the order processing settings to define for the site.
	* @return Mozu.Api.MozuClient <com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings>
	* @see com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings
	* @see com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings
	*/
	public static MozuClient<com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings> updateOrderProcessingSettingsClient(com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings orderProcessingSettings) throws Exception
	{
		String url = com.mozu.api.urls.commerce.settings.checkout.OrderProcessingSettingsUrl.updateOrderProcessingSettingsUrl();
		String verb = "PUT";
		Class<?> clz = com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings.class;
		MozuClient<com.mozu.api.contracts.sitesettings.order.OrderProcessingSettings> mozuClient = new MozuClient(clz);
		mozuClient.setVerb(verb);
		mozuClient.setResourceUrl(url);
		mozuClient.setBody(orderProcessingSettings);
		return mozuClient;

	}

	
}



