
/**
*     This code was auto-generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*/
package com.mozu.api.contracts.pricingruntime;

import java.util.ArrayList;
import java.io.Serializable;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.mozu.api.contracts.pricingruntime.ProductProperty;


/**
*	Properties of a line item in an order that is subject to tax.
*/
public class TaxableLineItem implements Serializable
{
	/** Default Serial Version UID  */
	private static final long serialVersionUID = 1L;

	/**
	*Unique identifier of the taxable line item.
	*/
	@JsonProperty("Id")
	protected String id;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	/**
	*If true, the line item in the order is subject to tax.
	*/
	@JsonProperty("IsTaxable")
	protected Boolean isTaxable;

	public Boolean getIsTaxable() {
		return this.isTaxable;
	}

	public void setIsTaxable(Boolean isTaxable) {
		this.isTaxable = isTaxable;
	}

	/**
	*The sale price of the line item in the order.
	*/
	@JsonProperty("LineItemPrice")
	protected Double lineItemPrice;

	public Double getLineItemPrice() {
		return this.lineItemPrice;
	}

	public void setLineItemPrice(Double lineItemPrice) {
		this.lineItemPrice = lineItemPrice;
	}

	@JsonProperty("ProductCode")
	protected String productCode;

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	/**
	*The quantity of the line item in the order.
	*/
	@JsonProperty("Quantity")
	protected Integer quantity;

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	*The amount of shipping calculated for a line item in an order.
	*/
	@JsonProperty("ShippingAmount")
	protected Double shippingAmount;

	public Double getShippingAmount() {
		return this.shippingAmount;
	}

	public void setShippingAmount(Double shippingAmount) {
		this.shippingAmount = shippingAmount;
	}

	/**
	*Properties of the product that represents the line item in the order.
	*/
	@JsonProperty("ProductProperties")
	protected ArrayList<ProductProperty> productProperties;
	public ArrayList<ProductProperty> getProductProperties() {
		return this.productProperties;
	}
	public void setProductProperties(ArrayList<ProductProperty> productProperties) {
		this.productProperties = productProperties;
	}

}
