/**
 *     This code was auto-generated by a tool.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.urls.commerce;

import com.mozu.api.MozuUrl;
import com.mozu.api.utils.UrlFormatter;


public class ChannelUrl
{

	/**
	 * Get Resource Url for GetChannels
	 * @param filter 
	 * @param pageSize 
	 * @param sortBy 
	 * @param startIndex 
	 * @return   String Resource Url
	 */
	public static MozuUrl getChannelsUrl(String filter, Integer pageSize, String sortBy, Integer startIndex)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/channels/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}");
		formatter.formatUrl("filter", filter);
		formatter.formatUrl("pageSize", pageSize);
		formatter.formatUrl("sortBy", sortBy);
		formatter.formatUrl("startIndex", startIndex);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for GetChannel
	 * @param code 
	 * @return   String Resource Url
	 */
	public static MozuUrl getChannelUrl(String code)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/channels/{code}");
		formatter.formatUrl("code", code);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for CreateChannel
	 * @return   String Resource Url
	 */
	public static MozuUrl createChannelUrl()
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/channels/");
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for UpdateChannel
	 * @param code 
	 * @return   String Resource Url
	 */
	public static MozuUrl updateChannelUrl(String code)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/channels/{code}");
		formatter.formatUrl("code", code);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for DeleteChannel
	 * @param code 
	 * @return   String Resource Url
	 */
	public static MozuUrl deleteChannelUrl(String code)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/channels/{code}");
		formatter.formatUrl("code", code);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

}

